### ISSUE TITLE
Ui doesn't work

### ISSUE THREAD

**Issue by Polocap2** [renzuzu/renzu_popui#1]
When I walk near the Icon I do get the menu like shown below:
https://imgur.com/a/qMmnOvd

But when I press E or Enter it flips the ui and I can't use it anymore like in the picture below.
https://imgur.com/a/OHMnZPx

Do you have any idea what might cause this issue?

**Comment by pedrox500** [comment]
Iam having the same problem, can we help us to get a quick fix?

**Comment by renzuzu** [comment]
is this still an issue?
i am not experiencing this problem in my side.
same version with the Popui here in my local

perhaps a f8 client error if you do have?

**Comment by Kille2323** [comment]
> is this still an issue?
> i am not experiencing this problem in my side.
> same version with the Popui here in my local
> 
> perhaps a f8 client error if you do have?

I also have the same problem.. but in F8 no client error..this just flips but garage or vechicle shop dont open..

**Comment by renzuzu** [comment]
Maybe theres an server error in garage or vehicleshop

**Comment by Kille2323** [comment]
> Maybe theres an server error in garage or vehicleshop

I tried it on localhost
